name: flutter_application_1
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:

  cupertino_icons: ^1.0.2
  get: ^4.6.5
  font_awesome_flutter: ^10.1.0
  flutter_screenutil: ^5.5.3+2
  rflutter_alert:
  get_storage:
  firebase_core: ^1.19.1
  firebase_auth: ^3.4.1
  cloud_firestore: ^3.1.14
  image_picker: ^0.8.4+9
  path_provider:
  path:

  flutter:
    sdk: flutter
  flutter_neumorphic: ^3.2.0
  google_fonts: ^3.0.0
  clay_containers: ^0.3.2

  pinput: ^2.2.9
  intl_phone_field: ^3.1.0
  intl_phone_number_input: ^0.7.0+2
  google_sign_in: ^5.3.2
  flutter_spinkit: ^5.1.0
  uuid: ^3.0.6
  cloud_functions: ^3.3.1
  firebase_storage: ^10.3.1
  animated_splash_screen: ^1.3.0
  flutter_lorem: ^2.0.0
  chewie: ^1.3.4
  video_player: ^2.4.5
  


dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_launcher_icons: "^0.9.2"
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/lunch_icon/lunch_icon-01.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/welcome_screans/
    - assets/splash_screen/
    - assets/images/authorization_screen/
    - assets/images/authorization_screen/tribel_signs/
    - assets/icons/
